### ISSUE TITLE
Thoughts on SSR?

### ISSUE THREAD

**Issue by stevewillard** [hoppula/react-apig-lambda#1]
Great repo! Have you thought about adding in support for server side rendering? I'd be particularly interested in how to hook that up with apex deployments and API Gateway.

**Comment by hoppula** [comment]
That's actually the gist of this repo :) Like stated in the description: `Initial server-side render and acts as SPA from there.`  Lambda does the server rendering.

[Recent addition of proxy resources to API Gateway](https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/) inspired me to create this repo in first place, as doing SSR with API Gateway and Lambda is now really simple compared to what it used to be.

**Comment by stevewillard** [comment]
Whoops! I completely missed the render.js part of this project. Awesome!
